### ISSUE TITLE
建议增加默认的项目目录

### ISSUE THREAD

**Issue by weiSmile** [helinjiang/generator-grunt-h5#1]
建议以项目名做默认的项目目录。若当前目录没该文件夹则新建，有则直接在该目录下建立项目结构

**Comment by helinjiang** [comment]
不错的建议，在0.2.1中进行优化。

但关于“本目录中已经存在文件的情况下是否要新建一个额外的子文件夹，并将工程建在子文件夹中”，这个做法并不可取，基于以下两点来考虑：

第一，我参考了 `yeoman` 官方推荐的几个项目生成器，都没有做这种优化，全部都是在当前目录生成项目，而无论当前目录中是否已经存在文件。如果已经存在相同文件，则 `yeoman` 已有 [机制](http://yeoman.io/authoring/file-system.html) 用于提示是否覆盖。我认为这已经足够了。

第二，正常情况下，我们使用 Node.js ，通常首先是 `cd` 到某个路径下，这也意味着我们的操作就是针对这个目录的，至于当前目录中是否存在其他文件，大多数情况下需要自己来考虑。例如最典型的就是我们执行 `npm install` 时，包就会直接安装在当前目录下，而不是再新建文件。

综上，我们推荐用户自己来保证是否存在文件夹的判断，但为了更好的体验，我们会在当前文件夹下存在其他文件的情况下，提示： `Warning! This directory you want to scaffold into already exist files or folders! Please be careful!` 。仅仅是提示，如果你执意继续，则忽略之。
